### ISSUE TITLE
OpenCl on OS X

### ISSUE THREAD

**Issue by jamescoxon** [jamescoxon/nano_distributed_pow_client#11]
Been trying to setup up libmpow (or mpow) with opencl on OS X,

After adding `-framework OpenCL` to the makefile and changed `cl_command_queue queue = clCreateCommandQueueWithProperties(context, device_id, 0, NULL);` to `cl_command_queue queue = clCreateCommandQueueWithPropertiesAPPLE(context, device_id, 0, NULL);` the binaries compile but it doesn't seem like OpenCl is used (instead there is a single thread running which doesn't seem to ever finish.

I added some debug:
`
=== 1 OpenCL platform(s) found: ===
  -- 0 --
  PROFILE = FULL_PROFILE
  VERSION = OpenCL 1.2 (Jan  4 2017 22:35:59)
  NAME = Apple
  VENDOR = Apple
  EXTENSIONS = cl_APPLE_SetMemObjectDestructor cl_APPLE_ContextLoggingFunctions cl_APPLE_clut cl_APPLE_query_kernel_names cl_APPLE_gl_sharing cl_khr_gl_event
`

**Comment by ghost** [comment]
This happens because opencl error codes were not processed before. I've added statements (77790f3) in the code to pinpoint which opencl function is failing. The error code returned can be checked in the link below to understand why that specific function is failing.

https://streamhpc.com/blog/2013-04-28/opencl-error-codes/

Unfortunately, I've no access to a system with OS X to add apple specific macros and functions.

**Comment by jamescoxon** [comment]
While its now works its painfully slow (as in >30seconds per work while CPU is 5-15seconds) - any ideas why or is it just a poor GPU (Intel HD 4000)

**Comment by ghost** [comment]
I think that's the reason. And it's not just Apple. It has always been like that with onboard GPUs. And it makes sense. Onboard GPUs are usually 300MHz and like 8 cores or something. Unless you've an actual GPU it doesn't make sense to use opencl.

**Comment by ghost** [comment]
The actual comparison I'm interested in is, if you can compute a lot of work using the work server on GPU and the same number of work using this code, again on gpu and compare the statistics.
