### ISSUE TITLE
Unable to install on OS X

### ISSUE THREAD

**Issue by jamescoxon** [jamescoxon/nano_distributed_pow_client#18]
`running install`
`running bdist_egg`
`running egg_info`
`creating nano_dpow_client.egg-info`
`writing nano_dpow_client.egg-info/PKG-INFO`
`writing dependency_links to nano_dpow_client.egg-info/dependency_links.txt`
`writing requirements to nano_dpow_client.egg-info/requires.txt`
`writing top-level names to nano_dpow_client.egg-info/top_level.txt`
`writing manifest file 'nano_dpow_client.egg-info/SOURCES.txt'`
`reading manifest file 'nano_dpow_client.egg-info/SOURCES.txt'`
`writing manifest file 'nano_dpow_client.egg-info/SOURCES.txt'`
`installing library code to build/bdist.macosx-10.6-intel/egg`
`running install_lib`
`running build_ext`
`building 'mpow' extension`
`creating build`
`creating build/temp.macosx-10.6-intel-3.6`
`/usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c mpow.c -o build/temp.macosx-10.6-intel-3.6/mpow.o -fopenmp`
`clang: error: unsupported option '-fopenmp'`
`clang: error: unsupported option '-fopenmp'`
`error: command '/usr/bin/clang' failed with exit status 1`

Suspect that we need to select GCC not Clang.

**Comment by ghost** [comment]
b2fe0be should fix this issue. You can verify on OSX and close this issue.

However, if you look in the commit, you can see that the instructions are slightly different so that the user can install the client like a normal program and invoke it from anywhere inside his/her environment. So I renamed client.py --> client. May be we need a new name for the file. And the new name should replace "client" in setup.py, performance_check.py, and README.md.

**Comment by guilhermelawless** [comment]
Client renamed in 8d47eafe1409497a95a7322924c353ff3ef253d5
